- lib.nix
Until now `terranix` always exited without error, even if `nix-build` failed, which made it impossible to script with.
> Return exit code on failure, use safe bash options

- core/terraform-options.nix
i need [provider aliasing][1]
example config:
```nix
provider.docker = [
{
alias = "local";
host = "unix:///run/docker.sock";
}
];
```
[1]: https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-instances
> support provider aliasing

- flake.nix
Use `pkgs.formats.json` to format the JSON output. This allows for easier human reading of the generated config.
> terranixConfiguration: format generated json

- doc/Makefile
- doc/man-terranix-doc_description.refsection.xml
- doc/man-terranix-doc_options.refsection.xml
- doc/man-terranix_functions.refsection.md
- doc/man-terranix_functions.refsection.xml
- doc/man-terranix_hcl.refsection.md
- doc/man-terranix_hcl.refsection.xml
- doc/man-terranix_modules.refsection.md
- doc/man-terranix_modules.refsection.xml
Fix some typos in the docs.
Reason for other changes:
- I couldn't figure out how to run the build to get the current output.  In my pandoc (the latest fron nixpkgs unstable), the `docbook+smart` option fails with `The extension smart is not supported for docbook`.  This looks like it also broke nixpkgs [two years ago](https://github.com/NixOS/nixpkgs/commit/83015ff7954a1a111737359ac644443327ce6f6f) and the fix is to get rid of the `+smart`.
- I also removed the `xmlns` `sed` command from the `Makefile` because, otherwise, it was being duplicated.  I assume the newer pandoc just adds `xmlns` correctly.
> fix a few typos in docs

- core/default.nix
Makes it possible to use `resource.foo = mapAttrs ...` correctly with an empty attrset.
Not sure which other attributes should we handle like this.
> Remove empty resource and data types

- core/default.nix
- core/terraform-options.nix
After this pr being merged, if user has a definition of `resource.aws_s3_bucket.my_s3_bucket` and he would like to reference attributes of such resource in other places, instead of writing `"\${aws_s3_bucket.my_s3_bucket.arn}"`, he could use `config.resource.aws_s3_bucket.my_s3_bucket "arn"`, which produces a same string.
> Make resource and data referenceable

- core/default.nix
- tests/terranix-tests/12.nix
- tests/terranix-tests/12.nix.output
- tests/test.nix
This allows a nicer way to create terraform reference strings, without having to perform escaping:
```
{ lib, ... }:
{
resource.foo.bar = {
a-reference = lib.tfRef "data.another-resource.id";
};
}
```
> Add tfRef to lib available from within terranix modules

- flake.nix
- tests/test.nix
On my system, one test fails:
```
✗ terranix-doc-json: works with simple module
(from function `assert_output' in file /nix/store/wq1qq2yhaxldcq0ll9ms54zw789xpy5p-source/src/assert_output.bash, line 194,
in test file /nix/store/9dnr0i46zj79qbqabh9bfp9n5s8pkaca-test, line 164)
`assert_output '{"testing-terranix.enable":{"declarations":[{"channelPath":"/01.nix","path":"01.nix","url":"http://example.com/01.nix"}],"default":false,"description":"Whether to enable enable testing-terranix.","example":true,"loc":["testing-terranix","enable"],"readOnly":false,"type":"boolean"}}'' failed
-- output differs --
expected : {"testing-terranix.enable":{"declarations":[{"channelPath":"/01.nix","path":"01.nix","url":"http://example.com/01.nix"}],"default":false,"description":"Whether to enable enable …
```
> Pin tests to avoid failures due to different nixpkgs versions

- core/terraform-options.nix
A definition for option 'module.acm.source' is not of type 'bool, int, float or str'
Before: A definition for option 'module.acm.source' is not of type ''.
> fix: error message on types

- core/default.nix
- modules/provider/cloudflare.nix
- modules/provisioner.nix
- modules/terraform/backends.nix
to avoid false leads when assessing the target system context of pkgs, don't declare it in scope here
If tests are green, then this was probably a valid cleanup :smile: 
I tried `nix flake check`:
```console
terranix on  cleanup-be-explicit-about-consuming-or-not-pkgs
❯ nix flake check
warning: unknown flake output 'lib'
warning: flake output attribute 'defaultPackage' is deprecated; use 'packages.<system>.default' instead
warning: flake output attribute 'devShell' is deprecated; use 'devShells.<system>.default' instead
warning: flake output attribute 'defaultApp' is deprecated; use 'apps.<system>.default' instead
warning: flake output attribute 'defaultTemplate' is deprecated; use 'templates.default' instead
terranix on  cleanup-be-explicit-about-consuming-or-not-pkgs took 26s
❯ echo …
```
> fix: pkgs is not consumed in this scope

- .envrc
- .gitignore
For `direnv`: https://direnv.net/
A.f.a.i.k. there is debate over whether `.envrc` should be checked-in or not. There are good reasons to reject this PR; i.e. a developer who uses `direnv` but who does not use Nix Flakes. The `.envrc` in this PR would be bad for that developer.
> check in `.envrc`

- core/terraform-invocs.nix
- flake.nix
This PR adds a helper function, `terranix.lib.mkTerranixOutputs`, to simplify how you'd declare `nix run .#apply` and `nix run .#destroy`.
- It takes a `terraformConfiguration` to create a symlink of the terraform of the configuration in the current directory
- It optionally takes a custom `terraform` derivation (useful for wrapping `terraform` invocations in environments with secret envvars, like shown in the documentation)
From this, it generates `apply` and `destroy` scripts with the logic above prepended, as well as corresponding `app` outputs as well as a `devShell` for optional added ergonomy (compare `apply` to `nix run .#apply`)
Sample usage:
```nix
inherit (inputs.terranix.lib.mkTerranixOutputs {
inherit pkgs;
terraform = pkgs.writeShellApplication {
name = "terraform"; …
```
> add terraform invocation wrapping

- flake-module.nix
- flake.nix
This allows the terranix flake-parts options to show up on https://flake.parts/
I've intentionally targeted the `main` branch as I don't believe there are any breaking changes here and will allow [flake.parts-website](https://github.com/hercules-ci/flake.parts-website) to use this code earlier
<details><summary>Rendered</summary>
[terranix](https://terranix.org/) is a terraform.json generator with a nix-like feeling.
To use these options, add to your flake inputs:
```nix
terranix.url = "github:terranix/terranix";
```
and inside the `mkFlake`:
```nix
imports = [
inputs.terranix.flakeModule
];
```
Run `nix flake lock` and you're set.
Whether to set default ` devShell ` or not\. By default enabled\.
You can disable this if you want to customize the ` devShell ` creation youself or otherwise …
> Fix documentation for flake-parts module

- core/default.nix
Reopening with `main` target because https://github.com/terranix/terranix/pull/110 got closed
> fix: add float to sanitize

- flake-module.nix
Reopening because previous PR targeting `develop` got closed. Explanation in https://github.com/terranix/terranix/pull/109
> feat: Improve flake-parts module

- README.md
There doesn't seem to be a Matrix server at terranix.org anymore and the room's address has been updated to #terranix:nixos.org. So while clicking the link works, copying the address to a matrix client does not.
Also: I tried to contact you in that room regarding maintenance.
> :memo: update matrix channel name

- flake-module.nix
Helps docs eval performance a bit and makes deployment to flake.parts work.
> chore: Avoid evaluating terraform package for option docs

- flake-module.nix
Within the terraform wrapper we ensure the directory is created, however the `ln` happens before that. Ensure the workdir exists before linking the tf json.
> fix: Ensure workspace exists in flake-parts module scripts

- .envrc
- dev/flake-module.nix
- dev/flake.lock
- dev/flake.nix
- flake.lock
- flake.nix
This is using the flake-parts feature partitions in order to move inputs not needed by third-party consumers into a separate dev flake.
This reduces the amount of inputs that gets inherited by downstream users.
> refactor: separate dev inputs

- flake-module.nix
I removed this option as it should always be equal to `submod.config.terraformWrapper.package.meta.mainProgram`
I couldn't find any uses of it on GitHub: https://github.com/search?utf8=%E2%9C%93&q=path%3A*.nix%20terraformWrapper%20mainProgram%20-is%3Afork&type=code
> flake-module: fix wrapper for `opentofu` called `terraform`

- flake-module.nix
The TF config was added to `scripts` which meant that it tried to get used as a build input when building a `devShell`. It should instead be directly added to the `passthru` so that it is still accessible using `.#my-terranix-configuration.config`.
> flake-module: fix `devShells` failing to build

- flake-module.nix
Fixes the following error, so docs can be published on flake.parts again.
```
… from call site
at /nix/store/ri9gj1alzk2apqfvrvzx6p6m6r5n52sx-source/flake-module.nix:34:35:
33|                       terraformWrapper = {
34|                         package = mkPackageOption pkgs "terraform" {
|                                   ^
35|                           example = "pkgs.opentofu";
error: function 'mkPackageOption' called with unexpected argument 'description'
at /nix/store/80jiav8nl8hsx2sf4miaihfacajn1i5h-source/lib/options.nix:311:7:
310|       name:
311|       {
|       ^
312|         nullable ? false,
```
> flake-parts: Fix documentation eval

- flake-module.nix
When `terranixConfigurations.default` exists, the scripts were erroneously being set to `packages` flake output instead of `apps`
> flake-parts: Separate `apps` from `packages` output

- flake-module.nix
- flake.nix
This change removes the reference to `inputs.terranix` used in the flake module, so the module can be used also in flake-parts based flakes that do not import terranix directly, but only as a transitive dependency.
Now it is irelevant, where the terranix flake resides in inputs, whether it is at `inputs.terranix` (as required now) or e.g. as `inputs.some-flake.inputs.terranix.
> fix(flake-parts): Do not require terranix to be in root of inputs
